name: Fetch Images

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  fetch-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This line grants the GITHUB_TOKEN permission to push commits to the repository
    strategy:
      matrix:
        script: [nytimes.sh]  # Add more script names here as you create them

    steps:
    - uses: actions/checkout@v2

    - name: Set up ImageMagick and Poppler Utils
      run: |
        sudo apt-get update
        sudo apt-get install imagemagick poppler-utils -y

    - name: Fetch Images
      run: . generate-images/${{ matrix.script }}

    - name: Commit and Push Images
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add images/nytimes.png
        git commit -m "Update images" || echo "No changes to commit"
        git push
